name: Build binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Compile
        run: |
          pyinstaller --noconsole --onefile uac_wrapper.spec
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/pyWinContext.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
